---
title: "x06-WebScraping"
author: "Brandon Leff"
output:
  html_document:
    df_print: paged
---

```{r}
include <- function(library_name){
  if( !(library_name %in% installed.packages()) )
    install.packages(library_name) 
  library(library_name, character.only=TRUE)
}
include("rvest")
include("tidyverse")
```

```{r}
myurl <- "http://ems.csuchico.edu/APSS/schedule/spr2020/MATH.shtml"
testmath20 <- read_html(myurl)
bran <- testmath20 %>% html_node(css = "table")
don <- bran %>%  html_table(header = TRUE) %>% 
  mutate(nc = nchar(Sect)) %>%
  filter(nc==2)
beforetable <-  don %>% tibble(subject = don$Subj,
                               catnum = don$'Cat Num',
                               section = don$Sect,
                               title = don$Title,
                               instructor = don$Instructor,
                               tot_enrl = don$'Tot Enrl')
finaltable <- beforetable %>% select(subject,catnum,section,title,instructor,tot_enrl)
```

```{r}
read_class_schedule <- function(url){
  midfun <- read_html(url)
  midtbl <- html_node(midfun, css="table")
  pretib <- midtbl %>%
  html_table(header = TRUE) %>% 
  mutate(nc = nchar(Sect)) %>%
  filter(nc==2)
  tblname <- pretib %>% tibble(subject = pretib$Subj,
                               catnum = pretib$'Cat Num',
                               section = pretib$Sect,
                               title = pretib$Title,
                               instructor = pretib$Instructor,
                               tot_enrl = pretib$'Tot Enrl')
  return(tblname)
}
```

```{r}
math2019 <- read_class_schedule("http://ems.csuchico.edu/APSS/schedule/spr2019/MATH.shtml") %>% select(subject,catnum,section,title,instructor,tot_enrl)
math2020 <- read_class_schedule("http://ems.csuchico.edu/APSS/schedule/spr2020/MATH.shtml") %>% select(subject,catnum,section,title,instructor,tot_enrl)
csci2019 <- read_class_schedule("http://ems.csuchico.edu/APSS/schedule/spr2019/CSCI.shtml") %>% select(subject,catnum,section,title,instructor,tot_enrl)
csci2020 <- read_class_schedule("http://ems.csuchico.edu/APSS/schedule/spr2020/CSCI.shtml") %>% select(subject,catnum,section,title,instructor,tot_enrl)
math <- rbind(math2019,math2020)
csci <- rbind(csci2019,csci2020)
schedules <- rbind(math,csci)
```


